# -*- coding: utf-8 -*-
"""ML PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cis3nHs88iXAcV4dd7369qapKo4LyYy3
"""

# PHASE-1(CUSTOM DATASET & CLUSTERING)
#Load-Inspect Data & Define Columns Names
import pandas as pd
import numpy as np

column_names = ['unit','time'] + [f'operational_set{i}' for i in range(1,4)] + [f'sensor{i}' for i in range(1,22)]

combinations = {
    "FD001_FD003": ["train_FD001.txt", "train_FD003.txt"],
    "FD002_FD004": ["train_FD002.txt", "train_FD004.txt"],
    "FD001_FD002_FD003_FD004": ["train_FD001.txt", "train_FD002.txt", "train_FD003.txt", "train_FD004.txt"]
}

clustered_data = {}

#Preprocessing for Each Combination
from sklearn.preprocessing import StandardScaler

for combo_name, files in combinations.items():
    all_data = []
    for file in files:
        df = pd.read_csv(file, sep='\s+', header=None)
        df.columns = column_names
        df = df.dropna(axis=1)
        all_data.append(df)
    data = pd.concat(all_data, ignore_index=True)

    features = data.drop(['unit', 'time'], axis=1)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(features)

    data_scaled = pd.DataFrame(X_scaled, columns=features.columns)
    clustered_data[combo_name] = {'raw': data, 'scaled': data_scaled}

#KMean Clustering
from sklearn.cluster import KMeans

for combo_name in clustered_data:
    kmeans = KMeans(n_clusters=5, random_state=42)
    labels = kmeans.fit_predict(clustered_data[combo_name]['scaled'])
    clustered_data[combo_name]['raw']['cluster'] = labels
clustered_data

#Analyze Clusters & Label Stages

for combo_name in clustered_data:
    print(f"\nCluster Means for {combo_name}:")
    mean_df = clustered_data[combo_name]['raw'].groupby('cluster').mean()
    print(mean_df.head())

#Assign Degradation Labels

cluster_stages={
    3:1,                    #Slightly degraded
    1:2,                    #Moderately degraded
    0:3,                    #Critical
    4:4,                    #Failure
    2:0                     #Normal
}

for combo_name in clustered_data:
    clustered_data[combo_name]['raw']['stages'] = clustered_data[combo_name]['raw']['cluster'].map(cluster_stages)

# Agglomerative Clustering
from sklearn.cluster import AgglomerativeClustering

for combo_name in clustered_data:
    data_scaled = clustered_data[combo_name]['scaled']
    sample_indices = np.random.choice(len(data_scaled), size=5000, replace=False)
    sample_data = data_scaled.iloc[sample_indices]

    agglo = AgglomerativeClustering(n_clusters=5)
    agglo_labels = agglo.fit_predict(sample_data)

    clustered_data[combo_name]['raw']['agg_cluster'] = -1
    clustered_data[combo_name]['raw'].loc[sample_indices, 'agg_cluster'] = agglo_labels

# PCA and t-SNE Visualization
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

def visualize_pca(df, title, label_col):
    features = df.drop(['unit','time','cluster','stages','agg_cluster'], axis=1, errors='ignore')
    pca = PCA(n_components=2)
    reduced = pca.fit_transform(features)

    plt.figure(figsize=(10,6))
    plt.scatter(reduced[:,0], reduced[:,1], c=df[label_col], cmap='viridis', s=3)
    plt.title(f"PCA - {title} ({label_col})")
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.colorbar(label=label_col)
    plt.grid(True)
    plt.show()

def visualize_tsne(df, title, label_col):
    features = df.drop(['unit','time','cluster','stages','agg_cluster'], axis=1, errors='ignore')
    tsne = TSNE(n_components=2, perplexity=30, n_iter=300, random_state=42)
    reduced = tsne.fit_transform(features)

    plt.figure(figsize=(10,6))
    plt.scatter(reduced[:,0], reduced[:,1], c=df[label_col], cmap='plasma', s=3)
    plt.title(f"t-SNE - {title} ({label_col})")
    plt.xlabel("Dim 1")
    plt.ylabel("Dim 2")
    plt.colorbar(label=label_col)
    plt.grid(True)
    plt.show()

for combo_name in clustered_data:
    df = clustered_data[combo_name]['raw']
    visualize_pca(df, combo_name, 'stages')
    visualize_tsne(df.sample(n=2000, random_state=42), combo_name, 'stages')
    visualize_pca(df[df['agg_cluster'] != -1], combo_name, 'agg_cluster')
    visualize_tsne(df[df['agg_cluster'] != -1].sample(n=2000, random_state=42), combo_name, 'agg_cluster')

# Save processed data
for name, dataset in clustered_data.items():
    dataset['raw'].to_csv(f"labeled_train_data_{name}.csv", index=False)

# PHASE-2(CLASSIFICATION USING RANDOM FOREST)
# import libraries for model training, evalution, visualization
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

#Load labeled data
import pandas as pd

data1 = pd.read_csv("labeled_train_data_FD001_FD003.csv")
data2 = pd.read_csv("labeled_train_data_FD002_FD004.csv")
data3 = pd.read_csv("labeled_train_data_FD001_FD002_FD003_FD004.csv")

all_datasets = [(data1, "FD001+FD003"), (data2, "FD002+FD004"), (data3, "FD001+FD002+FD003+FD004")]

#Add Rolling Statistics

rolling_sensors = ['sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor11', 'sensor15', 'sensor17']
for idx, (data, name) in enumerate(all_datasets):
    for sensor in rolling_sensors:
        data[sensor + '_mean'] = data.groupby('unit')[sensor].rolling(window=5, min_periods=1).mean().reset_index(level=0, drop=True)
        data[sensor + '_std'] = data.groupby('unit')[sensor].rolling(window=5, min_periods=1).std().reset_index(level=0, drop=True)
    data.fillna(0, inplace=True)
    all_datasets[idx] = (data, name)

#Train-Test Split
splits = []
for data, name in all_datasets:
    X = data.drop(['unit', 'time', 'cluster', 'stages'], axis=1)
    Y = data['stages']
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)
    splits.append((X_train, X_test, Y_train, Y_test, X.columns, name))

#Random Forest Classifier
rf_models = []
for X_train, X_test, Y_train, Y_test, columns, name in splits:
    rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    rf_model.fit(X_train, Y_train)
    Y_pred_rf = rf_model.predict(X_test)
    print(f"Random Forest Classification Report ({name}):")
    print(classification_report(Y_test, Y_pred_rf))

    #Confusion Matrix
    cm = confusion_matrix(Y_test, Y_pred_rf)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'Confusion Matrix - Random Forest ({name})')
    plt.show()

    rf_models.append((rf_model, X_train, X_test, Y_train, Y_test, columns, name))

# Plot Feature Importance from Random Forest
for rf_model, _, _, _, _, columns, name in rf_models:
    importances = rf_model.feature_importances_
    feat_imp = pd.DataFrame({'feature': columns, 'importance': importances}).sort_values(by='importance', ascending=False)
    plt.figure(figsize=(10,6))
    sns.barplot(data=feat_imp.head(20), x='importance', y='feature')
    plt.title(f'Top 20 Feature Importances - RF ({name})')
    plt.show()

#Logistic Regression
for X_train, X_test, Y_train, Y_test, _, name in splits:
    logreg = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
    logreg.fit(X_train, Y_train)
    Y_pred_logreg = logreg.predict(X_test)
    print(f"\nLogistic Regression Classification Report ({name}):")
    print(classification_report(Y_test, Y_pred_logreg))

    #Confusion Matrix
    cm_log = confusion_matrix(Y_test, Y_pred_logreg)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm_log, annot=True, fmt='d', cmap='Oranges')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'Confusion Matrix - Logistic Regression ({name})')
    plt.show()

#Handle Imbalance with SMOTE (help to balance the rare classes)
from imblearn.over_sampling import SMOTE

smote_results = []
for X_train, X_test, Y_train, Y_test, columns, name in splits:
    smote = SMOTE(random_state=42)
    X_train_smote, Y_train_smote = smote.fit_resample(X_train, Y_train)

    rf_model_smote = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    rf_model_smote.fit(X_train_smote, Y_train_smote)
    Y_pred_smote_rf = rf_model_smote.predict(X_test)
    print(f"\nRF After SMOTE ({name}):")
    print(classification_report(Y_test, Y_pred_smote_rf))

    logreg_smote = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
    logreg_smote.fit(X_train_smote, Y_train_smote)
    Y_pred_smote_logreg = logreg_smote.predict(X_test)
    print(f"\nLogistic Regression After SMOTE ({name}):")
    print(classification_report(Y_test, Y_pred_smote_logreg))

#Train XGBoost Classifier
from xgboost import XGBClassifier

for X_train, X_test, Y_train, Y_test, columns, name in splits:
    xgb = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
    xgb.fit(X_train, Y_train)
    Y_pred_xgb = xgb.predict(X_test)
    print(f"\nXGBoost Classification Report ({name}):")
    print(classification_report(Y_test, Y_pred_xgb))

    xgb_importance = pd.DataFrame({
        'feature': columns,
        'importance': xgb.feature_importances_
    }).sort_values(by='importance', ascending=False)

    plt.figure(figsize=(10,6))
    sns.barplot(x='importance', y='feature', data=xgb_importance.head(20))
    plt.title(f"Top 20 Feature Importances - XGBoost ({name})")
    plt.show()

# PHASE-3(REGRESSION- TIME TO NEXT DEGRADATION STAGE PREDICTION)

#Import and Load Data
import pandas as pd
import numpy as np

reg1 = pd.read_csv("labeled_train_data_FD001_FD003.csv")
reg2 = pd.read_csv("labeled_train_data_FD002_FD004.csv")
reg3 = pd.read_csv("labeled_train_data_FD001_FD002_FD003_FD004.csv")

reg_datasets = [(reg1, "FD001+FD003"), (reg2, "FD002+FD004"), (reg3, "FD001+FD002+FD003+FD004")]

#Compute Time to Next Stage
def compute_next_stage(df):
    df_sort = df.sort_values(['unit', 'time']).copy()
    df_sort['time_to_next_stage'] = np.nan

    for uid in df_sort['unit'].unique():
        unit_df = df_sort[df_sort['unit'] == uid].copy().reset_index()
        stages = unit_df['stages'].values
        time_left = [0] * len(stages)

        for i in range(len(stages)):
            count = 0
            for j in range(i + 1, len(stages)):
                count += 1
                if stages[j] != stages[i]:
                    time_left[i] = count
                    break

        df_sort.loc[unit_df['index'], 'time_to_next_stage'] = time_left

    df_sort = df_sort[df_sort['time_to_next_stage'] > 0]
    return df_sort

#Apply Time to Next Stage Computation
processed_reg = []
for df, name in reg_datasets:
    updated = compute_next_stage(df)
    processed_reg.append((updated, name))

#Import libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

#Train and Evaluate Random Forest Regressor
for df, name in processed_reg:
    X = df.drop(['unit','time','cluster','stages','time_to_next_stage'], axis=1)
    Y = df['time_to_next_stage']

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

    rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_reg.fit(X_train, Y_train)
    Y_pred = rf_reg.predict(X_test)

    print(f"\nRandom Forest Regressor Results ({name}):")
    print("MAE:", mean_absolute_error(Y_test, Y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred)))
    print("R^2:", r2_score(Y_test, Y_pred))

    plt.figure(figsize=(10,6))
    plt.scatter(Y_test, Y_pred, alpha=0.4)
    plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], 'r--')
    plt.xlabel("Actual Time to Next Stage")
    plt.ylabel("Predicted")
    plt.title(f"Actual vs Predicted - RF Regressor ({name})")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

#Train and Evaluate XGBoost Regressor
from xgboost import XGBRegressor

for df, name in processed_reg:
    X = df.drop(['unit','time','cluster','stages','time_to_next_stage'], axis=1)
    Y = df['time_to_next_stage']

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

    xgb_reg = XGBRegressor(n_estimators=100, random_state=42)
    xgb_reg.fit(X_train, Y_train)
    Y_pred = xgb_reg.predict(X_test)

    print(f"\nXGBoost Regressor Results ({name}):")
    print("MAE:", mean_absolute_error(Y_test, Y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred)))
    print("R^2:", r2_score(Y_test, Y_pred))

    plt.figure(figsize=(10,6))
    plt.scatter(Y_test, Y_pred, alpha=0.4)
    plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], 'r--')
    plt.xlabel("Actual Time to Next Stage")
    plt.ylabel("Predicted")
    plt.title(f"Actual vs Predicted - XGBoost Regressor ({name})")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# PHASE-4 (RISK SCORING)
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import matplotlib.pyplot as plt

reg1 = pd.read_csv("labeled_train_data_FD001_FD003.csv")
reg2 = pd.read_csv("labeled_train_data_FD002_FD004.csv")
reg3 = pd.read_csv("labeled_train_data_FD001_FD002_FD003_FD004.csv")

combinations = [(reg1, "FD001+FD003"), (reg2, "FD002+FD004"), (reg3, "FD001+FD002+FD003+FD004")]

#Define compute_next_stage function
def compute_next_stage(df):
    df_sort = df.sort_values(['unit', 'time']).copy()
    df_sort['time_to_next_stage'] = np.nan

    for uid in df_sort['unit'].unique():
        unit_df = df_sort[df_sort['unit'] == uid].copy().reset_index()
        stages = unit_df['stages'].values
        time_left = [0] * len(stages)

        for i in range(len(stages)):
            count = 0
            for j in range(i + 1, len(stages)):
                count += 1
                if stages[j] != stages[i]:
                    time_left[i] = count
                    break

        df_sort.loc[unit_df['index'], 'time_to_next_stage'] = time_left

    df_sort = df_sort[df_sort['time_to_next_stage'] > 0]
    return df_sort

#Train Classifier and Predict Stage 4 Probability
for i in range(len(combinations)):
    df, name = combinations[i]
    X_class = df.drop(['unit','time','cluster','stages'], axis=1)
    Y_class = df['stages']
    clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
    clf.fit(X_class, Y_class)
    df['P_stage_4'] = clf.predict_proba(X_class)[:, 4]
    combinations[i] = (df, name)

#Compute Time to Next Stage
for i in range(len(combinations)):
    df, name = combinations[i]
    reg_df = compute_next_stage(df)
    combinations[i] = (reg_df, name)

#Train Regressor and Predict Time to Next Stage (with sampling)
for i in range(len(combinations)):
    reg_df, name = combinations[i]
    if len(reg_df) > 30000:
        reg_df = reg_df.sample(n=30000, random_state=42)
    X_reg = reg_df.drop(['unit','time','cluster','stages','time_to_next_stage','P_stage_4'], axis=1)
    Y_reg = reg_df['time_to_next_stage']
    reg = RandomForestRegressor(n_estimators=100, random_state=42)
    reg.fit(X_reg, Y_reg)
    reg_df['predicted_time_to_next_stage'] = reg.predict(X_reg)
    combinations[i] = (reg_df, name)

#Compute Risk Scores
for i in range(len(combinations)):
    reg_df, name = combinations[i]
    reg_df['raw_risk_score'] = reg_df['P_stage_4'] * reg_df['predicted_time_to_next_stage']

    min_risk, max_risk = reg_df['raw_risk_score'].min(), reg_df['raw_risk_score'].max()

    reg_df['normalized_risk_score'] = (reg_df['raw_risk_score'] - min_risk) / (max_risk - min_risk)
    reg_df['inverted_risk_score'] = reg_df['P_stage_4'] / (reg_df['predicted_time_to_next_stage'] + 1e-6)
    combinations[i] = (reg_df, name)

#Trigger Maintenance Alerts
for i in range(len(combinations)):
    reg_df, name = combinations[i]
    reg_df['alert'] = reg_df['normalized_risk_score'].apply(lambda x: "⚠️ Maintenance Alert!" if x > 0.7 else "")
    combinations[i] = (reg_df, name)

#Display and Plot Risk Insights
for reg_df, name in combinations:
    risk_rank = reg_df.sort_values(by='normalized_risk_score', ascending=False)
    print(f"\nTop High-Risk Units - {name}")
    print(risk_rank[['unit','time','P_stage_4','predicted_time_to_next_stage','normalized_risk_score','alert']].head(10))

    top_risk = risk_rank.head(10)
    plt.figure(figsize=(10,6))
    plt.barh(top_risk['unit'].astype(str)+"_t"+top_risk['time'].astype(int).astype(str), top_risk['normalized_risk_score'])
    plt.xlabel("Normalized Risk Score")
    plt.ylabel("Engine Unit")
    plt.title(f"Top High-Risk States - {name}")
    plt.gca().invert_yaxis()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    unit_id = int(risk_rank.iloc[0]['unit'])
    unit_data = reg_df[reg_df['unit'] == unit_id]
    plt.figure(figsize=(10,6))
    plt.plot(unit_data['time'], unit_data['normalized_risk_score'], marker='o')
    plt.xlabel("Time")
    plt.ylabel("Normalized Risk Score")
    plt.title(f"Risk Score over Time - Unit {unit_id} ({name})")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

#Precision-Recall Curve for Threshold Tuning
from sklearn.metrics import precision_recall_curve, average_precision_score

for reg_df, name in combinations:
    y_true = (reg_df['normalized_risk_score'] > 0.7).astype(int)
    y_scores = reg_df['normalized_risk_score']
    precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
    avg_precision = average_precision_score(y_true, y_scores)

    plt.figure(figsize=(8,6))
    plt.plot(recall, precision, marker='.', label=f'Avg Precision = {avg_precision:.2f}')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title(f'Precision-Recall Curve - {name}')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()